### ISSUE TITLE
有3.1.5的res吗

### ISSUE THREAD

**Issue by Nuist666** [TeyvatL/GrasscutterTool-3.1.5#1]

**Comment by Sycamore0** [comment]
你猜
![image](https://user-images.githubusercontent.com/64587684/193746894-5fe25224-fbb5-4052-9e70-5c0e9217f1e9.png)

**Comment by Nuist666** [comment]
在哪哇

**Comment by moux23333** [comment]
v 1btc for leak

**Comment by Nuist666** [comment]
我有了嘿嘿
![image](https://user-images.githubusercontent.com/104258411/193793529-9c2ca7bd-68c5-4540-8937-942614b4fc28.png)

**Comment by Dr-WeiAL** [comment]
> 我有了嘿嘿 ![image](https://user-images.githubusercontent.com/104258411/193793529-9c2ca7bd-68c5-4540-8937-942614b4fc28.png)

老哥哪搞的啊(
